# Generated by Django 2.0.7 on 2018-08-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(choices=[('1', 'AUTOMATIC'), ('2', 'MANUAL'), ('3', 'SEMIAUTO')], default='MANUAL', max_length=10)),
                ('upholst', models.CharField(choices=[('1', 'CLOTH'), ('2', 'LEATHER')], default='CLOTH', max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('typeOfEngine', models.CharField(choices=[('1', 'DIESEL'), ('2', 'GASOLINE'), ('3', 'ELECTRIC')], max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ModelOfCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.ModelOfCar'),
        ),
    ]
