# Generated by Django 2.0.7 on 2018-09-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(max_length=10)),
                ('upholst', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('typeOfEngine', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('priceAbroad', models.CharField(max_length=10, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ModelOfCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carscompare.ModelOfCar'),
        ),
    ]
