# Generated by Django 2.0.7 on 2018-08-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carscompare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('1', 'AUTOMATIC'), ('2', 'MANUAL'), ('3', 'SEMIAUTO')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='typeOfEngine',
            field=models.CharField(choices=[('1', 'DIESEL'), ('2', 'GASOLINE'), ('3', 'ELECTRIC')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='upholst',
            field=models.CharField(choices=[('1', 'CLOTH'), ('2', 'LEATHER')], default='1', max_length=10),
        ),
    ]
