# Generated by Django 2.0.7 on 2018-08-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carscompare', '0002_auto_20180816_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='typeOfEngine',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='upholst',
            field=models.CharField(max_length=10),
        ),
    ]
