# Generated by Django 2.0.7 on 2018-08-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carscompare', '0003_auto_20180818_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
