# Generated by Django 2.0.7 on 2018-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carscompare', '0004_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='priceAbroad',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
