# Generated by Django 2.0.7 on 2018-09-11 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(null=True)),
                ('rate', models.CharField(max_length=6, null=True)),
            ],
            options={
                'ordering': ['date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('typeOfObject', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=600, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.City')),
            ],
            options={
                'ordering': ['rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('icon', models.ImageField(blank=True, upload_to='media/')),
                ('obj', models.ManyToManyField(null=True, to='carsbg.Object')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayWork', models.CharField(max_length=30)),
                ('saturday', models.CharField(max_length=30)),
                ('sunday', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='workingTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.WorkingTime'),
        ),
        migrations.AddField(
            model_name='comment',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.Object'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.Profile'),
        ),
    ]
