# Generated by Django 2.0.7 on 2018-07-06 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tel',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
