# Generated by Django 2.0.7 on 2018-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='ratingDisplay',
            field=models.IntegerField(null=True),
        ),
    ]
