# Generated by Django 2.0.7 on 2018-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0004_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
