# Generated by Django 2.0.7 on 2018-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0005_auto_20180707_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardealer',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cardealer',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cardealer',
            name='tel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
