# Generated by Django 2.0.7 on 2018-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0006_auto_20180708_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='typeOfObject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='typeOfObject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
