# Generated by Django 2.0.7 on 2018-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0010_auto_20180714_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
