# Generated by Django 2.0.7 on 2018-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0011_auto_20180721_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
