# Generated by Django 2.0.7 on 2018-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0012_auto_20180721_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
