# Generated by Django 2.0.7 on 2018-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0013_auto_20180725_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
