# Generated by Django 2.0.7 on 2018-07-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0016_auto_20180725_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='lenOfRatings',
        ),
        migrations.RemoveField(
            model_name='service',
            name='lenOfRatings',
        ),
    ]
