# Generated by Django 2.0.7 on 2018-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0017_auto_20180725_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dealer',
        ),
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
