# Generated by Django 2.0.7 on 2018-08-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0021_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
