# Generated by Django 2.0.7 on 2018-08-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0022_auto_20180816_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Object',
        ),
        migrations.RemoveField(
            model_name='cardealer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cardealer',
        ),
        migrations.DeleteModel(
            name='CarDealer',
        ),
    ]
    atomic = False
