# Generated by Django 2.0.7 on 2018-08-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0023_auto_20180831_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='service',
            new_name='obj',
        ),
    ]
