# Generated by Django 2.0.7 on 2018-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0024_auto_20180831_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['name']},
        ),
    ]
