# Generated by Django 2.0.7 on 2018-09-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0026_auto_20180831_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayWork', models.CharField(max_length=30)),
                ('weekend', models.CharField(max_length=30)),
                ('sunday', models.CharField(max_length=30)),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.Object')),
            ],
        ),
    ]
