# Generated by Django 2.0.7 on 2018-09-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0027_workingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingtime',
            old_name='weekend',
            new_name='saturday',
        ),
    ]
