# Generated by Django 2.0.7 on 2018-09-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0028_auto_20180908_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='obj',
        ),
        migrations.AddField(
            model_name='object',
            name='workingTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsbg.WorkingTime'),
        ),
    ]
