# Generated by Django 2.0.7 on 2018-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0032_auto_20180908_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
