# Generated by Django 2.0.7 on 2018-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0033_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
