# Generated by Django 2.0.7 on 2018-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsbg', '0034_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='obj',
        ),
        migrations.AddField(
            model_name='service',
            name='obj',
            field=models.ManyToManyField(null=True, to='carsbg.Object'),
        ),
    ]
